### ISSUE TITLE
chrome extension利用時のコンテンツの表示位置が不規則に移動

### ISSUE THREAD

**Issue by tmkawanabe** [SIPupstreamDesign/ChOWDER#10]
chrome extension を利用してauto capture=on, interval=0.5secで表示しているGoogle Docs(slide)の画面が、仮想ディスプレイ上で不規則に移動する。その際、ディスプレイ側でも同様にコンテンツ位置が移動する。（エビデンス映像をメールで送付）

**Comment by uimac** [comment]
すみません、こちら再現しないです。起きた時のコントローラのブラウザは何でしょうか？

**Comment by tmkawanabe** [comment]
mac osx10.11.6 上のchrome（テスト時点で最新版）です。
