### ISSUE TITLE
Controller: movieコンテンツ追加時にdisplay表示モードだとコンテンツ操作ができなくなる

### ISSUE THREAD

**Issue by tmkawanabe** [SIPupstreamDesign/ChOWDER#13]
Controller画面において、Display表示モードのまま、Add->Movieすると、Controller画面上では何も起きていないように見える。（Displayデバイス上にはコンテンツが現れる）

Contents表示モードに移行しても、コンテンツ一覧にも表示されないため、移動も削除もできなくなる。

コンテンツ追加時は、自動的にContent表示モードに移行するのがよいのではないでしょうか？

**Comment by uimac** [comment]
> Controller画面において、Display表示モードのまま、Add->Movieすると、Controller画面上では何も起きていないように見える。（Displayデバイス上にはコンテンツが現れる）
↑ こちらは再現しなかったので、
> コンテンツ追加時は、自動的にContent表示モードに移行する
の対応のみ行い、pullreqしました。
https://github.com/SIPupstreamDesign/ChOWDER/pull/19

**Comment by tmkawanabe** [comment]
本日長時間いじってみましたが、上記の不具合は発現しませんでしたのでクローズします。
