### ISSUE TITLE
redisをリセットする方法

### ISSUE THREAD

**Issue by tmkawanabe** [SIPupstreamDesign/ChOWDER#15]
既報の通り、過去に登録したコンテンツがredis上には残るが、コントローラ画面上で表示されないことが多々あります。（確実な再現方法を見つけていませんが、かなりの頻度です）

そこで、とりあえずの対処法として、redisの内容をクリアする方法が知りたいのですが、どうしたらよいでしょうか？

**Comment by uimac** [comment]
以下のいずれのかの方法で可能です。
・setting→managementから、DBを新規作成すると、DBの新しい領域にコンテンツが記憶されます。
・redis.exeがあるディレクトリ内にできる"dumb.rdb"というファイルを消すと、DB完全削除となり、完全に何も記録されていない状態から開始できます(groupやパスワードなども消えるので注意)。
