### ISSUE TITLE
extension_for_WebRTCのmanifest.jsonに記述するサーバアドレスについて

### ISSUE THREAD

**Issue by tmkawanabe** [SIPupstreamDesign/ChOWDER#16]
これはシグナリングサーバのアドレスですよね？

manifestには、決め打ちのアドレスをひとまず書き込んでおいて、実行時に別ファイルから読み込んだアドレスで設定を上書き（あるいは追加）するような処理は可能でしょうか？

**Comment by uimac** [comment]
はい、シグナリングサーバのアドレスです。
正確には、ユーザーがChOWDER  Controllerページを開いているときのURLです。

chrome及びchromeウェブストアはローカルファイルアクセスできませんので不可能と思われます。
webpage←→extension間の通信はmanifest.jsonのexternally_connectableを設定する以外ではできないです。
webpage←→extension間をwebsocket(localhost、ポート固定)で接続し、screen shareの情報を交換できないか試してみます。

**Comment by uimac** [comment]
websocket接続を試そうとしましたが、socket通信を許可するにはmanifest.jsonに
"sockets" : { ... }という記載が必要で、これはchrome extensionでは出来なくてchrome appでしか対応していないようでした。
しかしchrome appではwebpage←→chrome app間でのdesktopCaptureができません。
