### ISSUE TITLE
Movieファイルを縮小表示したとき、原寸サイズをトリミングしたような表示になるときがある

### ISSUE THREAD

**Issue by tmkawanabe** [SIPupstreamDesign/ChOWDER#21]
コントローラ仮想ディスプレイエリア左上の動画ファイルは、約1/2サイズに縮小して表示していますが、ディスプレイデバイス（写真後ろ）上では、トリミングしたように表示されています。

動画再生開始時は正常なのですが、再生途中から原寸トリミングしたようになってしまいます。コンテンツを一旦ディスプレイデバイス外部の領域に移動して、また中に戻す（P2P再接続を期待）操作をすると、正常な縮小状態に戻ります。が、またトリミング状態になったりする。必ずなるわけではないですが、一度なると高確率でなります。

<img width="1483" alt="2018-03-17 18 21 41" src="https://user-images.githubusercontent.com/4436421/37553709-98da5c02-2a10-11e8-84be-0601f0541003.png">

**Comment by uimac** [comment]
しばらく試しましたが再現しないです。既に他の修正で直っている可能性があります
