### ISSUE TITLE
表示出来ない動画ファイルがある

### ISSUE THREAD

**Issue by tmkawanabe** [SIPupstreamDesign/ChOWDER#22]
Addメニューからファイル指定しても、ドラッグアンドドロップしても、コンテンツ一覧に表示されない。

別途、当該動画ファイルをお送りします。

**Comment by uimac** [comment]
動画ファイルを確認しましたところ、コーデックがApple ProRes422になっており、
非対応のためブラウザで読み込み/再生できないです。
現在のChOWDERの動画再生は、基本的にH.264のMP4のみ対応しています。
H.264のmovに限っては中身がフォーマット的にH.264のMP4と同一のようです。

**Comment by tmkawanabe** [comment]
確認ありがとうございます。了解しました。
