### ISSUE TITLE
動画ビットレート設定不良？　ビットレートの確認方法

### ISSUE THREAD

**Issue by tmkawanabe** [SIPupstreamDesign/ChOWDER#25]
RaspberryPi等の低性能なH/Wをディスプレイデバイスにすると、動画の表示が追いつきません。fpsが遅くなるが、コマ落ちするのではなく、再生が追いつかなくなる感じ。コントローラ上の再生が終了すると、ディスプレイ側は再生途中でも終了します。

動画のビットレートを下げることで、解消できるか試していますが、極端に小さな値（例：最大32k, 最小16kなど）にしても、再生品質は「自動」の場合と変わりはないように見えます。

実際のビットレート設定値を確認する方法はありますか？

**Comment by tmkawanabe** [comment]
ビットレートの設定はできるが、設定後の実際のビットレートを取得することはできない、ということでしょうか？

もし実際のビットレートを取得できるようでしたら、コンソールログにでも出力していただけると助かります。

**Comment by uimac** [comment]
webrtcのステータスとしてbytesReceivedという値が取れていましたので、
PR: #33 にて受信した動画のビットレートをコンソールログに出すようにしてみました。
Ctrl+Shift+i にてdeveloper toolを出し, コンソールのFilterに"bitrate:"と入力すると確認できます。
