### ISSUE TITLE
osx El capitan, Firefox60.2.2ESRにて、httpsのコントローラ認証画面に入力欄が表示されない

### ISSUE THREAD

**Issue by tmkawanabe** [SIPupstreamDesign/ChOWDER#37]
<img width="1280" alt="2018-10-15 11 34 38" src="https://user-images.githubusercontent.com/4436421/47078513-722a9a00-d23e-11e8-8274-899c07f945a5.png">

**Comment by uimac** [comment]
こちらでも現象確認しました。
https://CHOWDER_SERVER_URL:9091/
を開いて、websocketで使用しているポート(9091)の例外設定をブラウザに追加する必要があります。

**Comment by tmkawanabe** [comment]
了解です。その旨ドキュメントに記載をお願いいたします
