### ISSUE TITLE
ドキュメント　Electron版ディスプレイアプリの記述について

### ISSUE THREAD

**Issue by tmkawanabe** [SIPupstreamDesign/ChOWDER#38]
原点が左上であること、座標が[横,縦]であることを追記してください。
サンプルが[500,500]なのが分かりづらい原因のような気もします。[1920,1280]とかのほうがいいかも。

あと以下の部分、行末のカンマが抜けています。
```
"position": [0, 0]
```

**Comment by uimac** [comment]
こちらUserGuideを修正しました.
