### ISSUE TITLE
Electron版ディスプレイアプリのlocalhost以外での利用方法

### ISSUE THREAD

**Issue by tmkawanabe** [SIPupstreamDesign/ChOWDER#41]
質問です。
リモートホストでstandalone_electronを使う場合、以下の手順でよいでしょうか。
（手順をドキュメントに追記して下さい）

1) リモートホストにnode.jsがインストールされていること
2) standalone-electron/ 以下のファイル・ディレクトリをリモートホストの任意のパスに配置
3) リモートホストの standalone-electron/conf.jsonを適宜編集
4) リモートホストの standalone-electron/ 直下で npm start を実行

**Comment by uimac** [comment]
> リモートホストにnode.jsがインストールされていること
node.js及びstandalone_electronのインストールは、[ChOWDERのインストール](https://github.com/SIPupstreamDesign/ChOWDER/blob/master/UserGuide/jp/UserGuide.md#%E3%82%A2%E3%83%97%E3%83%AA%E3%82%B1%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%AE%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB%E6%96%B9%E6%B3%95)に含まれています。
standalone_electron単体でインストールする場合のドキュメントということでしょうか。

使用方法は
[Electron版ChOWDERディスプレイアプリケーションの利用](https://github.com/SIPupstreamDesign/ChOWDER/blob/master/UserGuide/jp/UserGuide.md#Electron%E7%89%88ChOWDER%E3%83%87%E3%82%A3%E3%82%B9%E3%83%97%E3%83%AC%E3%82%A4%E3%82%A2%E3%83%97%E3%83%AA%E3%82%B1%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%AE%E5%88%A9%E7%94%A8)
の項にありますが、もう少し詳しく書いてみます

**Comment by uimac** [comment]
ChOWDERのインストールと同時に、パッケージ化されたElectron版ディスプレイアプリがインストールされるようにしました。npm startでの実行ではなく、exeをダブルクリックで起動するようになります。
[Electron版ChOWDERディスプレイアプリケーションの利用](https://github.com/SIPupstreamDesign/ChOWDER/blob/201903/UserGuide/jp/UserGuide.md#Electron%E7%89%88ChOWDER%E3%83%87%E3%82%A3%E3%82%B9%E3%83%97%E3%83%AC%E3%82%A4%E3%82%A2%E3%83%97%E3%83%AA%E3%82%B1%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%AE%E5%88%A9%E7%94%A8)
の説明も変更しました。

**Comment by tmkawanabe** [comment]
ChOWDER-Standalone-Electron-*-x64/ 以下を他のマシンにコピーすればコピー先でも動く、という認識でよいでしょうか？

**Comment by uimac** [comment]
はい、ChOWDER-Standalone-Electron-*-x64/ 以下を他のマシンにコピーすればコピー先でも動きます。

**Comment by tmkawanabe** [comment]
了解です。その旨一言マニュアルに記載していただけないでしょうか

**Comment by uimac** [comment]
リモートホストへのインストール
リモートホストへ、実行ファイルを含む以下のフォルダをコピーし、実行することで、リモートホスト上でもElectron版ChOWDERディスプレイが起動します
・・・

と書いてますが、いかがでしょうか。

**Comment by tmkawanabe** [comment]
すみません、見落としていました。
