### ISSUE TITLE
201903  tileimage.sh error

### ISSUE THREAD

**Issue by tmkawanabe** [SIPupstreamDesign/ChOWDER#43]
以下のようなエラーとなりました。
送信元、サーバともosx, nodeはnodebrewのstable, ブラウザはchromeです。
最後のwarning行の表示から数分待っても何も起きませんでした。

'''
$ sh ./tileimage.sh output_NICAM_RAW_12x8x1_Greys_Map_4K_000.jpg 
Config file: /Users/tkawanabe/ChOWDER/ChOWDER/tileimage/config.json
Image file: /Users/tkawanabe/ChOWDER/ChOWDER/bin/output_NICAM_RAW_12x8x1_Greys_Map_4K_000.jpg
WebSocket connection established
Logged in as APIUser
Thumbnail generated
Group id: group_default
(node:4349) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
'''

**Comment by tmkawanabe** [comment]
tileimage送信元のコントローラ画面では何も起きませんでしたが、別のPCのブラウザで見ると以下のようにメタデータはサーバに届いているようです。（送信元のコントローラに表示されないのはなぜでしょう）

<img width="1321" alt="スクリーンショット 2019-03-19 15 39 23" src="https://user-images.githubusercontent.com/4436421/54585375-3ef26e00-4a5d-11e9-9a15-6901d8c30fa2.png">

**Comment by uimac** [comment]
$ sh ./tileimage.sh output_NICAM_RAW_12x8x1_Greys_Map_4K_000.jpg --metadata='{"time":"01234"}'
といった形でmetadataを入れる必要があります。
metadataが無いデータも受け付けるようにしたほうがよろしいでしょうか？

**Comment by tmkawanabe** [comment]
なるほど了解です。引数ごとにoptionalか否かをユーザマニュアルに記載してください

**Comment by uimac** [comment]
こちら対応しました。
ユーザーマニュアルにも記載しました。
なお、1枚の場合は大丈夫ですが、複数枚の時系列をmetadata無しで登録した場合は、あとから発行されたデータで上書きされていくため、最も最後に登録されたもの1枚のみが表示されます。
