### ISSUE TITLE
201903branch tileimage.sh warn

### ISSUE THREAD

**Issue by tmkawanabe** [SIPupstreamDesign/ChOWDER#45]
32Kのjpg画像(503MB)を送信したら、以下のwarningが出力されました。

$ sh ./tileimage.sh --metadata="{\"key\":\"000\"}" output_NICAM_RAW_12x8x1_Greys_Map_32K_000.jpg
Config file: /Users/tkawanabe/ChOWDER/ChOWDER/tileimage/config.json
Metadata: {"key":"000"}
Image file: /Users/tkawanabe/ChOWDER/ChOWDER/bin/output_NICAM_RAW_12x8x1_Greys_Map_32K_000.jpg
WebSocket connection established
Logged in as APIUser
Thumbnail generated
Group id: group_default
(node:4633) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Thumbnail sent
Tiled image processing: 58%
(sharp:4633): GLib-GObject-WARNING **: invalid uninstantiatable type '(null)' in cast to 'GObject'

(sharp:4633): GLib-GObject-CRITICAL **: g_object_set_qdata: assertion 'G_IS_OBJECT (object)' failed

(sharp:4633): GLib-GObject-WARNING **: invalid uninstantiatable type '(null)' in cast to 'GObject'

(sharp:4633): GLib-GObject-CRITICAL **: g_object_set_qdata: assertion 'G_IS_OBJECT (object)' failed

(sharp:4633): GLib-GObject-WARNING **: invalid uninstantiatable type '(null)' in cast to 'GObject'

(sharp:4633): GLib-GObject-CRITICAL **: g_object_set_qdata: assertion 'G_IS_OBJECT (object)' failed

(sharp:4633): GLib-GObject-WARNING **: invalid uninstantiatable type '(null)' in cast to 'GObject'

(sharp:4633): GLib-GObject-CRITICAL **: g_object_set_qdata: assertion 'G_IS_OBJECT (object)' failed
Tiled image processing: 92%%
(sharp:4633): GLib-GObject-WARNING **: invalid uninstantiatable type '(null)' in cast to 'GObject'

(sharp:4633): GLib-GObject-CRITICAL **: g_object_set_qdata: assertion 'G_IS_OBJECT (object)' failed
Tiled image processing: 75%
Done
Connection has been closed

**Comment by uimac** [comment]
sharpライブラリの中で使用されているGDK+から出ているようです。
解決方法を探したのですが今のところ不明です。動作上は問題なく動いているように見えます。

**Comment by tmkawanabe** [comment]
了解です。ではクローズします。
