### ISSUE TITLE
201903ブランチ PerformanceLogボタンが複数現れる

### ISSUE THREAD

**Issue by tmkawanabe** [SIPupstreamDesign/ChOWDER#46]
再現性は不明ですが、明示的にリロードせず、（マシンのスリープ・復帰などで）再接続されると起きるように思われます。
![IMG_0177](https://user-images.githubusercontent.com/4436421/54653751-158a1e80-4aff-11e9-9b7f-552b614e2bb1.jpg)

**Comment by uimac** [comment]
こちら修正しました. 201903から設計が変わったため、pull後にinstall.batを一度叩く必要があります.

**Comment by tmkawanabe** [comment]
最新版ではボタンは１つになりましたが、タイトルバーの下（コンテンツ表示領域）に現れます。タイトルバーとともに消えるので全画面表示では実害はありませんが、ご確認下さい（chromeで現象を確認）
