### ISSUE TITLE
201903ブランチ electron版ディスプレイ情報がコントローラに反映されない（ことがある）

### ISSUE THREAD

**Issue by tmkawanabe** [SIPupstreamDesign/ChOWDER#48]
１台のディスプレイクライアントPC(mac)に３台の物理ディスプレイをつなげて、ChOWDER-Standalone-Electron-darwin-x64を使っています。設定ファイルは以下の通り。起動すると正しく３つの論理ディスプレイは登録されコンテンツも表示されますが、コントローラ画面上に現れない論理ディスプレイがあります。
また、electron版ディスプレイを終了したとき、論理ディスプレイがコントローラ上から消去されないこともあります。

{
	"url": "http://172.19.56.75:8080/display.html",
	"password": "electronpassword",
	"windows": {
		"tile1-1": {
			"group": "group",
			"position": [0, 0],
			"size" : [3840, 2160],
			"vda_position": [0, 0],
			"vda_scale": 1.0,
			"fullscreen": true,
			"frame": false
		},
		"tile1-2": {
			"group": "group",
			"position": [0, 2160],
			"size" : [3840, 2160],
			"vda_position": [0, 2160],
			"vda_scale": 1.0,
			"fullscreen": true,
			"frame": false
		},
		"tile1-3": {
			"group": "group",
			"position": [0, 4320],
			"size" : [3840, 2160],
			"vda_position": [0, 4320],
			"vda_scale": 1.0,
			"fullscreen": true,
			"frame": false
		}
	}
}

**Comment by tmkawanabe** [comment]
追加情報：コントローラブラウザをリロードしても改善しませんが、ブラウザ表示サイズを変更すると、それまでリストに現れなかった論理ディスプレイが表示されるようです。

**Comment by uimac** [comment]
こちら修正完了しました
