### ISSUE TITLE
201903ブランチ electron版ディスプレイアプリで「コントローラ」を選択してから「ディスプレイ」に戻る方法がない？(t/o)

### ISSUE THREAD

**Issue by tmkawanabe** [SIPupstreamDesign/ChOWDER#50]

**Comment by uimac** [comment]
electron版ディスプレイアプリで「コントローラ」を使うことは想定していないので、
electron版ディスプレイアプリの場合は「Controller」「Display」のメニューを
メニューから削除してもよいでしょうか?

**Comment by tmkawanabe** [comment]
はい、そうしていただけるとわかりやすかと思います。

**Comment by uimac** [comment]
こちら、Electron版ディスプレイでは「Controller」「Display」のメニューが出ないように
修正しました
