### ISSUE TITLE
201903ブランチ　electron版ディスプレイで動画表示できない

### ISSUE THREAD

**Issue by tmkawanabe** [SIPupstreamDesign/ChOWDER#51]
ChOWDERサーバの8080ポートに接続しています。movieコンテンツが再生されません（黒いコンテンツウィンドウは表示される）
同じマシンからchromeをディプレイモードでサーバの8080ポートに接続すると動画は表示されます

**Comment by tmkawanabe** [comment]
ディスプレイ側はmac osx 10.14.3 です

**Comment by uimac** [comment]
こちらElectronのバージョンが古いのが問題でした。最新のものを入れるように修正しました。
pull後に、install.shを実行する必要があります。
