### ISSUE TITLE
201903ブランチ tileimage split_x=1, split_y=1 の設定時に表示がおかしい

### ISSUE THREAD

**Issue by tmkawanabe** [SIPupstreamDesign/ChOWDER#52]
split_x/y のどちらも1に設定すると、添付画像のように初期表示がおかしいです。
VDA上でコンテンツを操作（移動など）すると正常な表示状態になります。
![スクリーンショット 2019-04-03 18 36 42](https://user-images.githubusercontent.com/4436421/55468967-79ecc800-563f-11e9-85be-09f67b35f7bf.png)

**Comment by tmkawanabe** [comment]
このときは４K解像度画像をtileimage.shで送信しました。各物理ディスプレイに表示されているのは、そのサムネイルぽいです。

**Comment by uimac** [comment]
コンテンツIDを変えずに2回以上split_x/yを変えて送信している場合に起きるかもしれません（調査中）

**Comment by uimac** [comment]
こちらを見ていた時に確認された、同一コンテンツIDでsplit_x/yを変更して登録した時に、DB登録データがおかしくなっていた不具合を修正しました。
#53 ともに、修正範囲が大きいため、fixtileブランチを切って、そちらにプッシュしました

----

こちらのバグですが、正確な再現方法が分かっていません（再現していません）

同一コンテンツIDで、split_x/yを変更して上書き登録しようとした場合起きるのではないかと思い、
上記の通り、一部不具合を修正しましたが、再現しないため、直っているかは不明です。

split_x/yを変更して登録しようとした場合は、基本的に別IDで登録していただきたいと思いますので、エラーメッセージ出して登録を止めるのがいいかと思いますが、いかがでしょうか。
（時系列画像で途中の画像のみsplit_x/yが違う、といった状況には現在対応できないです）
