### ISSUE TITLE
202003ブランチ pdfを極端に拡大すると表示されなくなる

### ISSUE THREAD

**Issue by tmkawanabe** [SIPupstreamDesign/ChOWDER#62]
添付のpdfを横20kくらいに（VDA上で）拡大すると、表示されなくなります（コントローラのVDA上にsad macみたいなアイコンが出ます）　また、16Kくらいまで拡大したときは、コンテンツの一部が表示されなくなります。
[斜め罫線.pdf](https://github.com/SIPupstreamDesign/ChOWDER/files/4358255/default.pdf)

**Comment by uimac** [comment]
こちら幅x高さ=200000000超えたあたりにブラウザの制限があるようで、値はブラウザごとにも異なると思われます。
PDFをスケールして、8K以上となった場合は、canvas内部のPDFレンダリングを8K相当で行うように変更しました。
