### ISSUE TITLE
iOS9.3.5のsafariでfull screen mode不可

### ISSUE THREAD

**Issue by tmkawanabe** [SIPupstreamDesign/ChOWDER#9]
iPad model:MD515J/A にて

**Comment by uimac** [comment]
iOSでフルスクリーンにするためには、一度Displayを開いて、「ホーム画面に追加」を行い、
ホーム画面に出来たアイコンをクリックすることで、フルスクリーンになります

**Comment by tmkawanabe** [comment]
了解です。ありがとうございました。
